### ISSUE TITLE
Use local timezone to show start and end date

### ISSUE THREAD

**Issue by maoo** [finos/calendar#10]
Each event shows a start and end date, which is currently expressed using Eastern Timezone.

This task is to express these dates/times following the timezone passed by the browser.

**Comment by maoo** [comment]
Thanks for the feedback @mimiflynn . Are you suggesting a dropdown with some predefined timezones (ie EST and GMT), or the ability for the user to choose which timezones to configure (and probably remember for future sessions) ?

Depending on the complexity of the solution, we may want to track this feature as a separate issue.

**Comment by mimiflynn** [comment]
Good question! I can't currently include screenshots, but here are a [couple](https://www.thewindowsclub.com/how-to-display-two-time-zones-in-outlook-calendar) [links](https://www.workspacetips.io/tips/calendar/add-a-secondary-time-zone-to-google-calendar/) that show how Outlook and Google Calendar display different timezones. 

Our implementation won't need to be interactively configurable, as the timezones shown in addition to the users local timezone can be based on where we have the most membership.

I'm happy to work on this feature.

**Comment by TheJuanAndOnly99** [comment]
I've sent a PR that takes into account local timezone https://github.com/finos/calendar/pull/19. However, some events on the calendar are not in the default "EST" timezone and they do not convert properly.

**Comment by TheJuanAndOnly99** [comment]
This has been addressed by https://github.com/finos/calendar/pull/53. Thanks @maoo!
