### ISSUE TITLE
Event Detail Close action enhancements

### ISSUE THREAD

**Issue by mimiflynn** [finos/calendar#103]
Currently the event detail window close button is only on the inside of the detail and is hidden upon scroll. This makes it hard to browse through events. The user experience would be improved if:

- the close button and download buttons were sticky on the top of the event window
- the event window would close when the mouse is clicked outside the window
- the last event selected that was shown in the event window is highlighted
- the event window internal scroll state did not persist between events

**Comment by gautamjuyal** [comment]
I will try to work on the issue.

**Comment by gautamjuyal** [comment]
How should we display the last selected event? I tried to style it with an outline, how does this look? 
![Screenshot (397)](https://github.com/finos/calendar/assets/75676784/d06f39ab-a38d-4e0b-b4dc-2c1439c5058f)

**Comment by mimiflynn** [comment]
That's a good start! I feel a lighter colored background would pop a little more than the outline, perhaps grab lighter color from the 'today' button on the top left?

**Comment by gautamjuyal** [comment]
Sure. That sounds good. I'll try this out.
