### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by mimiflynn** [finos/calendar#105]
A couple of FINOS projects use Mocha, Jest, etc. Generally, [Jestjs ](https://jestjs.io/) is the preferred JavaScript testing framework.

The FDC3-Sail project is using [Vitest ](https://vitest.dev/) and [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) which looks like a good alternative, especially for those that are used to CRA. I'm going to use this, unless there is pushback from the team here.

**Comment by mimiflynn** [comment]
@maoo @TheJuanAndOnly99 do either of you have an opinion on the testing framework for this project?

**Comment by maoo** [comment]
Nope, all options you mention are fine.

Thanks for working on this! Although I'm not a super expert with NodeJS testing frameworks, I'd be happy to review the changes, when ready.
