### ISSUE TITLE
Create shareable deeplinks

### ISSUE THREAD

**Issue by mimiflynn** [finos/calendar#106]
"Deeplinks" are url parameters that enable a user to share a view state.

Consistent deeplinks should be available for the following view states:
- month view
- week view
- day view
- selected event
- downloadable calendar event .ics

**Comment by Amool-kk** [comment]
Hi @mimiflynn,

I am thrilled about the opportunity to contribute to this project and would love to work on this issue.

I would greatly appreciate it if you could provide me with more details about the issue, such as specific requirements, any existing discussions or proposed solutions, and any other relevant information that could guide me in the right direction.

**Comment by robmoffat** [comment]
Hi @Amool-kk,

Thrilled that you're interested in helping - do you want to have a crack at it, and let us know any specific questions you have?

**Comment by mimiflynn** [comment]
Closing this issue in favor of the discussion in the newer duplicate issue #127
