### ISSUE TITLE
Add "Download ICS" button on every event

### ISSUE THREAD

**Issue by maoo** [finos/calendar#12]
Code is partially done.

@TheJuanAndOnly99 - please create a branch with existing code and drop a comment with what's left to be done.

TY!

**Comment by TheJuanAndOnly99** [comment]
I've sent the draft PR https://github.com/finos/calendar/pull/18. It currently only works for single events. Would like to add recurring ones as well.

**Comment by TheJuanAndOnly99** [comment]
This has been addressed by https://github.com/finos/calendar/pull/53. Thanks @maoo!
