### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by psmulovics** [finos/calendar#13]
Add a dark mode (probably based on browser rule based on user settings too) possibility.

**Comment by gautamjuyal** [comment]
I would like to work on this issue.

**Comment by psmulovics** [comment]
We are glad for the offer! Is there anything we can help you with?

**Comment by gautamjuyal** [comment]
Thank you. It would help a lot if color schemes for dark theme were provided. We will also have to decide a position for manual theme switcher, if we should implement one.

**Comment by psmulovics** [comment]
I think a:
    background-color: #222;
    color: #eee;
would be working, @maoo ? @gautamjuyal , I think you should try it with this colors and we will see how it looks like:

![image](https://github.com/finos/calendar/assets/28162552/f70ea3e7-8333-4773-ae3d-ce0fcf262b59)

**Comment by mimiflynn** [comment]
Is this resolved with the above PR merge?
