### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by psmulovics** [finos/calendar#14]
Add a search bar on the top to search based on the text content of the entries, and hide items based on that.

**Comment by maoo** [comment]
Found this - https://yiengly.wordpress.com/2019/04/25/adding-filters-and-search-to-fullcalendar-events/

**Comment by gautamjuyal** [comment]
I would like to work on this issue.

**Comment by gautamjuyal** [comment]
How would we want the UX for search? The article above suggests that if there is a search term, display only the events that contain the search term, throughout the calendar. Should we have the same UX?

**Comment by gautamjuyal** [comment]
Thanks for the insights. I'll start working on it.

**Comment by gautamjuyal** [comment]
Is any contributor available for review?

**Comment by TheJuanAndOnly99** [comment]
Hi @gautamjuyal thanks for the PR! Just left a comment. I think we can marge soon :)

**Comment by gautamjuyal** [comment]
Glad to contribute :)

**Comment by maoo** [comment]
Given that the calendar cannot be previewed yet (@TheJuanAndOnly99 - maybe we can open an issue on this? I think it would be super helpful to have preview on PRs), it would be great to see some screenshots.

TY both!

**Comment by TheJuanAndOnly99** [comment]
@maoo there are screenshots in the [PR](https://github.com/finos/calendar/pull/94). I've also tested it locally on my machine. But yes I agree it would be nice to be able to have previews on PRs. I'll make an issue.

**Comment by maoo** [comment]
FWIW I also reviewed the PR, and looks great.

The only minor/stupid thing that comes to mind is the button color - shall we use a color that is used for the other buttons? Or the blue is intentional? Also, did you test it with dark mode? Not a blocker of course, can be adjusted after the merge.

**Comment by gautamjuyal** [comment]
@maoo It wasn't exactly intentional, the blue colors was used as bullet color for events in the calendar, I thought it might be good for light mode, but sure, we can change it to color used for other buttons. It is used in the dark mode anyway.
