### ISSUE TITLE
Proposal: Refactor to React

### ISSUE THREAD

**Issue by mimiflynn** [finos/calendar#21]
Overall, this is a proposal to use a framework / component library that will abstract away the HTML templating and state management aspects of JavaScript into a documented and approachable way.

I'm proposing React because I already know it and it not as heavy as Angular, my favorite enterprise front end framework. Using a tool I already know will help me get something out in a few hours and to best support anyone on this team that wants to contribute. The codebase will follow the basic best practices (nothing too complex to start) and allow those with React experience to contribute easily while allowing others to learn those practices.

I propose starting with [`create-react-app`](https://create-react-app.dev) as the base and to continue using [FullCalendar](https://github.com/fullcalendar/fullcalendar-react) with their React component.

Please let me know your thoughts.

**Comment by TheJuanAndOnly99** [comment]
Hi @mimiflynn I think this is a good idea! @maoo What do you think?

**Comment by maoo** [comment]
Like the idea, though I'd suggest to add [Svelte](https://svelte.dev/) in the list of potential frameworks 😉 

I don't expect many differences in the implementation, though in my experience, using Svelte results in cleaner and more performing code.

That said, I'll let you folks decide. @mimiflynn - feel free to raise a Pull Request and we can take it from there.

**Comment by mimiflynn** [comment]
I'll get something together! Thanks!

**Comment by mimiflynn** [comment]
Refactor branch merged
