### ISSUE TITLE
Duplicate Events

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/calendar#22]
Some events are being duplicated:
- KDB Project call 
- FINOS Diversity, Equity and Inclusion SIG - Monthly Meeting
- CDM Steering Working group
- and others 

Some are duplicated on https://calendar.google.com/calendar/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig%40group.calendar.google.com&ctz=Europe%2FMadrid (like CDM Collateral Working Group) which leads to the duplication. Others are not. Some are duplicated only on some occurrences and some are duplicated on every instance. Not sure why. Need to investigate.

**Comment by TheJuanAndOnly99** [comment]
The KDB project call is duplicated in the ics file of the Community Calendar which is leading to the duplication on [calendar.finos.org](calendar.finos.org). However, the other events that are duplicated (such as  FINOS Morphir Team Meeting on October 19th) are not duplicated in the ics file but are being duplicated on [calendar.finos.org](calendar.finos.org). However,  it is duplicated only on October 19th. The same is true for other events that are being duplicated, they only get duplicated sometimes. Past January 2024 there seem to be no more duplications (other than the KDB call coming from the ics file).

**Comment by psmulovics** [comment]
Is it related to the change in DST in the US vs UK happening at a different date?

**Comment by TheJuanAndOnly99** [comment]
Hi Peter I've been looking around but haven't found anyone facing similar issues so I've come up a bit short so far.

**Comment by psmulovics** [comment]
So can we just do a little processing in the part where we grab the file?

**Comment by TheJuanAndOnly99** [comment]
Fixed by https://github.com/finos/calendar/pull/53.
