### ISSUE TITLE
Mobile / small screen view

### ISSUE THREAD

**Issue by mimiflynn** [finos/calendar#35]
Currently, the calendar is not mobile friendly. Since the calendar is also embedded in a larger webpage, it might be best to focus the effort to viewport size instead of device type.

**Comment by TheJuanAndOnly99** [comment]
I implemented a few changes but there are still some improvements to be made. Especially around the popups.

**Comment by maoo** [comment]
Agreed. I propose the following list of items, ordered by priority:
- [ ] Show full calendar grid on screen without. the need of horizontal scrolling
- Improve event UI (take inspiration from Google Calendar)
  - [ ] Nicer Close (`x`) icon at the top right: use an icon instead of text
  - [ ] Add an icon for each item in the description
  - [ ] Place dates right below the event title, with a smaller font
  - [ ] Add the Location field (it's already in `events.json`)

**Comment by psmulovics** [comment]
Should not the mobile view be being more like an agenda and listing upcoming like 7 days' events?

**Comment by maoo** [comment]
> Should not the mobile view be being more like an agenda and listing upcoming like 7 days' events?

We could use the 7 days view by default on mobile, as it's already available in FullCalendar.

**Comment by gautamjuyal** [comment]
I would like to work on the issue.

**Comment by psmulovics** [comment]
Great, thank you! See above - as it is a mobile device we would want something slightly different than a monthly calendar, either a 7days view or an agenda view, etc, with a more full page overtake for the individual events

**Comment by maoo** [comment]
The default view is a full Calendar setting, see                                 `initialView="dayGridMonth"` on `App.jsx`.

Ideally, that setting should change based on screen width.

That said, every view should fit in the screen. Please refer to the specs listed on https://github.com/finos/calendar/issues/35#issuecomment-1841664492 and let me know if you have any questions.

Thanks @gautamjuyal

**Comment by gautamjuyal** [comment]
Thanks for the guidance @psmulovics @maoo. I'll let you know if if any problems come up

**Comment by gautamjuyal** [comment]
Is any contributor available to review the linked PR?

**Comment by maoo** [comment]
Sorry for the delay, I just added my review and passed to @TheJuanAndOnly99 - hopefully we can merge it by the end of the week. Thanks!

**Comment by gautamjuyal** [comment]
Happy to contribute
