### ISSUE TITLE
Empty description issue

### ISSUE THREAD

**Issue by gautamjuyal** [finos/calendar#76]
If an event has no description (field), the calendar crashes when the event is clicked.

![Screenshot (334)](https://github.com/finos/calendar/assets/75676784/b33ade02-356e-4617-ab69-478bbc1952a5)

![Screenshot (336)](https://github.com/finos/calendar/assets/75676784/e4dfc5bd-5fad-4e25-9dfd-3f15484a58ca)

**Comment by psmulovics** [comment]
Thank you for taking time to report this! Could you please help which event it was? I tried the spring bot project, but that seemed to work for me. My browser is Edge, are you on Chrome, Brave, etc any other browser?

**Comment by gautamjuyal** [comment]
Hey, can you check Spring Bot project from January 10, 2024? That event was causing crash for me on Chrome browser.

**Comment by psmulovics** [comment]
ah, thanks. I was going through only December events :)

**Comment by gautamjuyal** [comment]
Can I work on this, if other contributors are occupied at the moment?

**Comment by psmulovics** [comment]
Sure - go for it!

**Comment by TheJuanAndOnly99** [comment]
solved by https://github.com/finos/calendar/pull/78 thanks @gautamjuyal!
