### ISSUE TITLE
fc-popover popup is wrongly colored in dark mode

### ISSUE THREAD

**Issue by psmulovics** [finos/calendar#87]
As it is using the calculated variables, and they are not properly recalculated for dark mode, the fc-popovers do have the wrong colors:

![image](https://github.com/finos/calendar/assets/28162552/a9ca004d-39bb-4590-9152-fcfafd0e8a86)

**Comment by psmulovics** [comment]
@gautamjuyal, you wanna check this out?

**Comment by TheJuanAndOnly99** [comment]
Thanks @gautamjuyal!

**Comment by gautamjuyal** [comment]
Glad to contribute
